BookATable/ViewModels/Restaurants/RestaurantsCreateViewModel.cs
using BookATable.Entity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BookATable.ViewModels.Restaurants
{
    public class RestaurantsCreateViewModel
    {
        [Required]
        [StringLength(160, MinimumLength = 3, ErrorMessage = "Minimum length is 3 and maximum length is 160")]
        public string Name { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        [RegularExpression(@"^(\(?\+?[0-9]*\)?)?[0-9_\- \(\)\[\]]*$")]
        public string Phone { get; set; }
        [Required]
        [Range(1, 150)]
        public int Capacity { get; set; }
        [Required]
        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime OpenHour { get; set; }
        [Required]
        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime CloseHour { get; set; }

    }
}

BookATable/ViewModels/Restaurants/RestaurantsDeleteViewModel.cs
using BookATable.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookATable.ViewModels.Restaurants
{
    public class RestaurantsDeleteViewModel: BaseEntity
    {
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public int Capacity { get; set; }
        public DateTime OpenHour { get; set; }
        public DateTime CloseHour { get; set; }
    }
}

BookATable/ViewModels/Restaurants/RestaurantsEditViewModel.cs
using BookATable.Entity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BookATable.ViewModels.Restaurants
{
    public class RestaurantsEditViewModel: BaseEntity
    { 
        [Required(ErrorMessage = "Please input a name! It is required!")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "Minimum length is 3 and maximum length is 20")]
        [RegularExpression(@"^([A-z -]+)$", ErrorMessage = "Name can consist of letters, spaces and dashes only!")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please input a address! It is required!")]
        [StringLength(40, MinimumLength = 3, ErrorMessage = "Minimum length is 3 and maximum length is 40")]
        public string Address { get; set; }

        [RegularExpression(@"^(\(?\+?[0-9]*\)?)?[0-9_\- \(\)\[\]]*$")]
        public string Phone { get; set; }

        [Required]
        [Range(1, Int32.MaxValue)]
        public int Capacity { get; set; }

        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime OpenHour { get; set; }

        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime CloseHour { get; set; }
    }
}

BookATable/ViewModels/Restaurants/RestaurantsListViewModel.cs
using BookATable.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookATable.ViewModels.Restaurants
{
    public class RestaurantsListViewModel
    {
        public List<Restaurant> Restaurants { get; set; }
    }
}

BookATable/Controllers/RestaurantsController.cs
using BookATable.Data.Repositories;
using BookATable.Entity;
using BookATable.Filters;
using BookATable.ViewModels.Restaurants;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookATable.Controllers
{
    [AuthenticationFilter]
    public class RestaurantsController : Controller
    {
        public ActionResult Index()
        {
            RestaurantRepository repository = new RestaurantRepository();
            List<Restaurant> restaurants = repository.GetAll();

            RestaurantsListViewModel model = new RestaurantsListViewModel();
            model.Restaurants = restaurants;

            return View(model);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(RestaurantsCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            Restaurant restaurant = new Restaurant();
            restaurant.Name = model.Name;
            restaurant.Address = model.Address;
            restaurant.Phone = model.Phone;
            restaurant.Capacity = model.Capacity;
            restaurant.OpenHour = model.OpenHour;
            restaurant.CloseHour = model.CloseHour;

            var repository = new RestaurantRepository();
            repository.Insert(restaurant);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {

            RestaurantRepository repository = new RestaurantRepository();

            RestaurantsEditViewModel model = new RestaurantsEditViewModel();

            if (id.HasValue)
            {
                Restaurant restaurant = repository.GetByID(id.Value);
                model.ID = restaurant.ID;
                model.Address = restaurant.Address;
                model.Capacity = restaurant.Capacity;
                model.Phone = restaurant.Phone;
                model.Name = restaurant.Name;
                model.OpenHour = restaurant.OpenHour;
                model.CloseHour = restaurant.CloseHour;
 
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(RestaurantsEditViewModel model)
        {

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            RestaurantRepository repository = new RestaurantRepository();

            Restaurant restaurant = new Restaurant();
            restaurant.ID = model.ID;
            restaurant.Name = model.Name;
            restaurant.Address = model.Address;
            restaurant.Phone = model.Phone;
            restaurant.Capacity = model.Capacity;
            restaurant.OpenHour = model.OpenHour;
            restaurant.CloseHour = model.CloseHour;

            repository.Save(restaurant);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {

            RestaurantRepository repository = new RestaurantRepository();

            Restaurant restaurant = repository.GetByID(id);

            RestaurantsDeleteViewModel model = new RestaurantsDeleteViewModel();
            model.ID = restaurant.ID;
            model.Name = restaurant.Name;
            model.Address = restaurant.Address;
            model.Phone = restaurant.Phone;
            model.Capacity = restaurant.Capacity;
            model.OpenHour = restaurant.OpenHour;
            model.CloseHour = restaurant.CloseHour;

            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(RestaurantsDeleteViewModel model)
        {

            RestaurantRepository repository = new RestaurantRepository();

            repository.Delete(model.ID);

            return RedirectToAction("Index");
        }
    }
}

BookATable/Views/Restaurants/Create.cshtml
@model BookATable.ViewModels.Restaurants.RestaurantsCreateViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Restaurant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Capacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Capacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Capacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OpenHour, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OpenHour, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OpenHour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CloseHour, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CloseHour, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CloseHour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BookATable/Views/Restaurants/Delete.cshtml
@model BookATable.ViewModels.Restaurants.RestaurantsDeleteViewModel

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capacity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpenHour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpenHour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CloseHour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CloseHour)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BookATable/Views/Restaurants/Edit.cshtml
@model BookATable.ViewModels.Restaurants.RestaurantsEditViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Restaurant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Capacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Capacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Capacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OpenHour, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OpenHour, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OpenHour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CloseHour, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CloseHour, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CloseHour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BookATable/Views/Restaurants/Index.cshtml
@model BookATable.ViewModels.Restaurants.RestaurantsListViewModel

<h2>Restaurants</h2>
@{
    if (BookATable.Filters.AdminFilter.IsAdmin())
    {
        @Html.ActionLink("Create new", "Create", "Restaurants")
    }
}

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Address</th>
            <th>Phone</th>
            <th>Capacity</th>
            <th>OpenHour</th>
            <th>CloseHour</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var restaurant in Model.Restaurants)
        {
            <tr>
                <td>@restaurant.Name</td>
                <td>@restaurant.Address</td>
                <td>@restaurant.Phone</td>
                <td>@restaurant.Capacity</td>
                <td>@restaurant.OpenHour</td>
                <td>@restaurant.CloseHour</td>
           
                
                @{
                    if (BookATable.Filters.AdminFilter.IsAdmin())
                    {
                        <td>@Html.ActionLink("Edit", "Edit", "Restaurants", new { id = restaurant.ID }, new { @class = "btn btn-success glypchicon glyphicon-pencil" })</td>

                        <td>@Html.ActionLink("Delete", "Delete", "Restaurants", new { id = restaurant.ID }, new { @class = "btn btn-danger" })</td>

                    }
                }
                
            </tr>
        }
    </tbody>
</table>